QLKS/Controllers/ChucVusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS;
using QLKS.Models;

namespace QLKS.Controllers
{
    [MyAuthorize(Roles ="Admin,PM")]
    public class ChucVusController : Controller
    {
        private QLKSEntities2 db = new QLKSEntities2();
        // GET: ChucVus
        [ActionName("QuảnLýChứcVụ")]
        public ActionResult Index()
        {
            return View(db.ChucVu.ToList());
        }

        // GET: ChucVus/Details/5
        public ActionResult Details(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(x);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // GET: ChucVus/Create
        [ActionName("ThêmChứcVụ")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChucVus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("ThêmChứcVụ")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaCV,TenCV")] ChucVu chucVu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.ChucVu.Add(chucVu);
                    db.SaveChanges();
                    return View("ThêmChứcVụThànhCông");
                }
            }
            catch
            {
                return View("LỗiChứcVụ");
            }
            return View(chucVu);
        }

        // GET: ChucVus/Edit/5
        [ActionName("SửaChứcVụ")]
        public ActionResult Edit(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(x);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SửaChứcVụ")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaCV,TenCV")] ChucVu chucVu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(chucVu).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return View("SửaChứcVụThànhCông");
                }
            }
            catch
            {
                return View("LỗiChứcVụ");
            }
            return View(chucVu);
        }

        // GET: ChucVus/Delete/5
        [ActionName("XoáChứcVụ")]
        public ActionResult Delete(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(x);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVus/Delete/5
        [HttpPost, ActionName("XoáChứcVụ")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            ChucVu chucVu = db.ChucVu.Find(x);
            try
            {
                db.ChucVu.Remove(chucVu);
                db.SaveChanges();
                return View("XoáThànhCông");
            }
            catch
            {
                return View("LỗiXoáChứcVụ");
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKS/Controllers/NVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS;
using System.Text;
using QLKS.Models;
using PagedList;

namespace QLKS.Controllers
{
    [MyAuthorize(Roles ="Admin,PM")]
    public class NVsController : Controller
    {
       
       
        private QLKSEntities2 db = new QLKSEntities2();
        // Get: NVs
        [EncryptedActionParameter]
        [ActionName("TrangNhânViên")]
        [MyAuthorize(Roles ="PM")]
        public ActionResult Index(string option, string searchString,int? page)
        {
            var nVs = db.NV.Include(n => n.ChucVu);
            if(searchString!=null)
            {
                page = 1;
            }
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            
            if (option == "ChucVu")
            {
                return View(nVs.Where(x => x.ChucVu.TenCV.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "TenNV")
            {
                return View(nVs.Where(x => x.TenNV.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "SDT")
            {
                return View(nVs.Where(x => x.SDTNV.Contains(searchString)).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "MaNV")
            {
                return View(nVs.Where(x => x.MaNV.ToString().ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "DiaChi")
            {
                return View(nVs.Where(x => x.DCNV.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View(nVs.OrderBy(x=>x.MaNV).ToPagedList(pageNumber, pageSize));
            }
        }
        // GET: NVs/Details/5
        [ActionName("ThêmNhânViênTC")]
        public ActionResult Details(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NV nV = db.NV.Find(x);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // GET: NVs/Create
        [ActionName("ThêmNhânViên")]
        public ActionResult Create()
        {
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach(var item in db.ChucVu)
            {
                if(item.MaCV!=1 && item.MaCV!=2 && item.MaCV!=3)
                {
                    selectList.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList;
            return View();
        }

        // POST: NVs/Create
        [HttpPost]
        [ActionName("ThêmNhânViên")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,TenNV,MaCV,SDTNV,DCNV")] NV nV)
        {
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var item in db.ChucVu)
            {
                if (item.MaCV != 1 && item.MaCV != 2 && item.MaCV != 3)
                {
                    selectList.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList;
            try
            {
                if (ModelState.IsValid)
                {
                    db.NV.Add(nV);
                    db.SaveChanges();
                    return RedirectToAction("ThêmNhânViênTC", new { id = Encryption.encrypt(nV.MaNV.ToString()) });
                }
            }
            catch
            {
                return View("LỗiTạoNhânViên");
            }
            return View(nV);
        }

        // GET: NVs/Edit/5
        [MyAuthorize(Roles = "Admin,PM")]
        [EncryptedActionParameter]
        [ActionName("SửaNhânViên")]
        public ActionResult Edit(string id)
        {
            List<SelectListItem> selectList1 = new List<SelectListItem>();
            List<SelectListItem> selectList2 = new List<SelectListItem>();
            List<SelectListItem> selectList3 = new List<SelectListItem>();
            List<SelectListItem> selectList4 = new List<SelectListItem>();
            foreach (var item in db.ChucVu)
            {                
                  if(item.MaCV==1)
                  {
                    selectList1.Add(new SelectListItem
                        {
                            Text = item.TenCV,
                            Value = item.MaCV.ToString()
                        });
                  }
                    else if(item.MaCV==2 && item.MaCV!=1)
                    {
                    selectList2.Add(new SelectListItem
                        {
                            Text = item.TenCV,
                            Value = item.MaCV.ToString()
                        });

                    }
                else if (item.MaCV == 3 && item.MaCV != 1 && item.MaCV!=2)
                {
                    selectList3.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });

                }
                else if(item.MaCV!=1 || item.MaCV!=2 || item.MaCV!=3)
                {
                    selectList4.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV1 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList1;
            ViewBag.TenCV2 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList2;
            ViewBag.TenCV3 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList3;
            ViewBag.TenCV4 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList4;
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NV nV = db.NV.Find(x);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // POST: NVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SửaNhânViên")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,TenNV,MaCV,SDTNV,DCNV")] NV nV)
        {
            List<SelectListItem> selectList1 = new List<SelectListItem>();
            List<SelectListItem> selectList2 = new List<SelectListItem>();
            List<SelectListItem> selectList3 = new List<SelectListItem>();
            List<SelectListItem> selectList4 = new List<SelectListItem>();
            foreach (var item in db.ChucVu)
            {
                if (item.MaCV == 1)
                {
                    selectList1.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
                else if (item.MaCV == 2 && item.MaCV != 1)
                {
                    selectList2.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });

                }
                else if (item.MaCV == 3 && item.MaCV != 1 && item.MaCV != 2)
                {
                    selectList3.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });

                }
                else if (item.MaCV != 1 || item.MaCV != 2 || item.MaCV != 3)
                {
                    selectList4.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV1 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList1;
            ViewBag.TenCV2 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList2;
            ViewBag.TenCV3 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList3;
            ViewBag.TenCV4 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList4;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(nV).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return View("SửaNVTC");
                }
            }
            catch
            {
                return View("LỗiSửaNV");
            }
            return View(nV);
        }

        // GET: NVs/Delete/5
        [EncryptedActionParameter]
        [MyAuthorize(Roles = "Admin,PM")]
        [ActionName("XoáNhânViên")]
        public ActionResult Delete(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);

QLKS/Views/NVs/Details.cshtml
@model QLKS.NV

@{
    ViewBag.Title = "Thông tin nhân viên";
}


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DCNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DCNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChucVu.MaCV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChucVu.MaCV)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa thông tin", "Edit", new { id = Model.MaNV },new { @class = "btn btn-primary5" }) 
    @Html.ActionLink("Trở về danh sách nhân viên", "Index",null, new { @class = "btn btn-primary5" })
    @Html.ActionLink("Về trang chủ", "Index", "Home", null, new { @class = "btn btn-primary5" })
</p>

QLKS/Views/NVs/LỗiSửaNV.cshtml
@{
    ViewBag.Title = "LỗiSửaNV";
}

<h2>Cập nhật không thành công. Nhấp vào <a href="@Url.Action("TrangNhânViên")">đây</a> để quay về danh sách nhân viên.</h2>

QLKS/Views/NVs/LỗiTạonhânViên.cshtml
@{
    ViewBag.Title = "LỗiTạonhânViên";
}

<h2 style="color:red">Bạn không thể thêm nhân viên vì có thể mã nhân viên đã trùng với 1 nhân viên khác</h2>

QLKS/Views/NVs/LỗiXoáNV.cshtml
@{
    ViewBag.Title = "LỗiXoáNV";
}

<h2>Xóa nhân viên không thành công . Nhấp vào <a href="@Url.Action("TrangNhânViên")">đây</a> để quay về danh sách nhân viên.</h2>

QLKS/Views/NVs/SửaNVTC.cshtml
@{
    ViewBag.Title = "SửaNVTC";
}

<h2>Cập nhật nhân viên thành công! Nhấp vào <a style="color:red" href="@Url.Action("TrangNhânViên")">đây</a> để quay về danh sách nhân viên.</h2>

QLKS/Views/NVs/SửaNhânViên.cshtml
@model QLKS.NV

@{
    ViewBag.Title = "Sửa thông tin nhân viên";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>
        @{
            if (Model.MaCV == 1)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.ChucVu.TenCV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.MaCV, (IEnumerable<SelectListItem>)ViewBag.TenCV1, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else if (Model.MaCV == 2)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.ChucVu.TenCV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.MaCV, (IEnumerable<SelectListItem>)ViewBag.TenCV2, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else if (Model.MaCV == 3)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.ChucVu.TenCV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.MaCV, (IEnumerable<SelectListItem>)ViewBag.TenCV3, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.ChucVu.TenCV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.MaCV, (IEnumerable<SelectListItem>)ViewBag.TenCV4, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
        }

        <div class="form-group">
            @Html.LabelFor(model => model.SDTNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DCNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DCNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DCNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary1" />
            </div>
        </div>
    </div>
            }

<div>
    @Html.ActionLink("Trở về danh sách nhân viên", "TrangNhânViên", null, new { @class = "btn btn-primary5" })
    @Html.ActionLink("Về trang chủ", "TrangChủ", "Home", null, new { @class = "btn btn-primary5" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/NVs/ThêmNhânViên.cshtml
@model QLKS.NV

@{
    ViewBag.Title = "Trang thêm nhân viên";
}

<h2 >Thêm nhân viên</h2>
<hr style="color:black" />

@using (Html.BeginForm())
{
    
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChucVu.TenCV, "Tên chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaCV, (IEnumerable<SelectListItem>)ViewBag.TenCV, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ChucVu.TenCV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DCNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DCNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DCNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về danh sách nhân viên", "TrangNhânViên",null,new { @class="btn btn-primary5"})
    @Html.ActionLink("Về trang chủ","TrangChủ","Home",null,new { @class="btn btn-primary5"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/NVs/TrangNhânViên.cshtml
@model PagedList.IPagedList<QLKS.NV>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />
@using QLKS.Models
@{
    ViewBag.Title = "Quản lý nhân viên";
}


<p style="margin-top:30px;">
    <content style="margin-right:30px;">
        @Html.ActionLink("Thêm nhân viên", "ThêmNhânViên", null, new { @class = "btn btn-primary1" })
        @Html.ActionLink("Thêm chức vụ", "ThêmChứcVụ", "ChucVus", null, new { @class = "btn btn-primary1" })
    </content>
    @using (Html.BeginForm())
    {
    <p style="margin-top:30px;">
        Search Option: @Html.RadioButton("option", "ChucVu") <text>Chức vụ</text> | @Html.RadioButton("option", "MaNV") <text>Mã nhân viên</text> | @Html.RadioButton("option", "TenNV") <text> Tên Nhân Viên </text> |
        @Html.RadioButton("option", "SDT")<text>Số điện thoại</text> | @Html.RadioButton("option","DiaChi") <text>Địa chỉ NV</text> @Html.TextBox("searchString")
        <input type="submit" class="btn btn-primary1" name="submit" value="Search" />
    </p>
    }
<table style="border:1px solid black;margin-top:30px;" class="table">
    <tr style="border:1px solid black;">
        <th style="border:1px solid black;">
            Mã nhân viên
        </th>
        <th style="border:1px solid black;">
            Chức vụ
        </th>
        <th style="border:1px solid black;">
            Tên nhân viên
        </th>
        <th style="border:1px solid black;">
            Số điện thoại
        </th>
        <th style="border:1px solid black;">
            Địa chỉ
        </th>
        <th style="border:1px solid black;">
            Mã chức vụ
        </th>
        <th style="border:1px solid black;">
            <p style="text-align:center;">Chức năng</p>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr style="border:1px solid black;">
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.MaNV)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem=> item.ChucVu.TenCV)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.TenNV)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.SDTNV)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.DCNV)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.ChucVu.MaCV)
        </td>
        <td style="border:1px solid black;">
            @if (item.MaNV == 1 && item.MaNV == 2 && item.MaNV == 3)
            {
                @Html.ActionLink("Sửa", "SửaNhânViên", new { id = Encryption.encrypt(item.MaNV.ToString()) }, new { @class = "btn btn-primary1" })
            }
            else
            {
                @Html.ActionLink("Sửa", "SửaNhânViên", new { id = Encryption.encrypt(item.MaNV.ToString()) }, new { @class = "btn btn-primary1" })
                @Html.ActionLink("Xóa", "XoáNhânViên", new { id = Encryption.encrypt(item.MaNV.ToString()) }, new { @class = "btn btn-primary1" })
            }
       </td>
    </tr>
}

</table>
@if (Model.Count() > 0)
{

}
else
{
    <h5 style="color:red;">Thông tin bạn không tìm thấy</h5>
}
<p style="margin-left:500px;">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>

<div style="margin-left:450px;">
    @Html.PagedListPager(Model, page => Url.Action("TrangNhânViên",
    new { page }))
</div>
<p>@Html.ActionLink("Trở về danh sách","TrangNhânViên",null,new {@class= "btn btn-primary1" })</p>

QLKS/Views/NVs/XoáNVTC.cshtml
@{
    ViewBag.Title = "XoáNVTC";
}

<h2>Xóa nhân viên thành công. Nhấp vào <a href="@Url.Action("TrangNhânViên")">đây</a> để quay về danh sách nhân viên.</h2>