QLKS/Controllers/ChucVusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS;
using QLKS.Models;

namespace QLKS.Controllers
{
    [MyAuthorize(Roles ="Admin,PM")]
    public class ChucVusController : Controller
    {
        private QLKSEntities2 db = new QLKSEntities2();
        // GET: ChucVus
        [ActionName("QuảnLýChứcVụ")]
        public ActionResult Index()
        {
            return View(db.ChucVu.ToList());
        }

        // GET: ChucVus/Details/5
        public ActionResult Details(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(x);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // GET: ChucVus/Create
        [ActionName("ThêmChứcVụ")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChucVus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("ThêmChứcVụ")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaCV,TenCV")] ChucVu chucVu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.ChucVu.Add(chucVu);
                    db.SaveChanges();
                    return View("ThêmChứcVụThànhCông");
                }
            }
            catch
            {
                return View("LỗiChứcVụ");
            }
            return View(chucVu);
        }

        // GET: ChucVus/Edit/5
        [ActionName("SửaChứcVụ")]
        public ActionResult Edit(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(x);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SửaChứcVụ")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaCV,TenCV")] ChucVu chucVu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(chucVu).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return View("SửaChứcVụThànhCông");
                }
            }
            catch
            {
                return View("LỗiChứcVụ");
            }
            return View(chucVu);
        }

        // GET: ChucVus/Delete/5
        [ActionName("XoáChứcVụ")]
        public ActionResult Delete(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(x);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVus/Delete/5
        [HttpPost, ActionName("XoáChứcVụ")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            ChucVu chucVu = db.ChucVu.Find(x);
            try
            {
                db.ChucVu.Remove(chucVu);
                db.SaveChanges();
                return View("XoáThànhCông");
            }
            catch
            {
                return View("LỗiXoáChứcVụ");
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKS/Controllers/NVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS;
using System.Text;
using QLKS.Models;
using PagedList;

namespace QLKS.Controllers
{
    [MyAuthorize(Roles ="Admin,PM")]
    public class NVsController : Controller
    {
       
       
        private QLKSEntities2 db = new QLKSEntities2();
        // Get: NVs
        [EncryptedActionParameter]
        [ActionName("TrangNhânViên")]
        [MyAuthorize(Roles ="PM")]
        public ActionResult Index(string option, string searchString,int? page)
        {
            var nVs = db.NV.Include(n => n.ChucVu);
            if(searchString!=null)
            {
                page = 1;
            }
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            
            if (option == "ChucVu")
            {
                return View(nVs.Where(x => x.ChucVu.TenCV.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "TenNV")
            {
                return View(nVs.Where(x => x.TenNV.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "SDT")
            {
                return View(nVs.Where(x => x.SDTNV.Contains(searchString)).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "MaNV")
            {
                return View(nVs.Where(x => x.MaNV.ToString().ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "DiaChi")
            {
                return View(nVs.Where(x => x.DCNV.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View(nVs.OrderBy(x=>x.MaNV).ToPagedList(pageNumber, pageSize));
            }
        }
        // GET: NVs/Details/5
        [ActionName("ThêmNhânViênTC")]
        public ActionResult Details(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NV nV = db.NV.Find(x);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // GET: NVs/Create
        [ActionName("ThêmNhânViên")]
        public ActionResult Create()
        {
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach(var item in db.ChucVu)
            {
                if(item.MaCV!=1 && item.MaCV!=2 && item.MaCV!=3)
                {
                    selectList.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList;
            return View();
        }

        // POST: NVs/Create
        [HttpPost]
        [ActionName("ThêmNhânViên")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,TenNV,MaCV,SDTNV,DCNV")] NV nV)
        {
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach (var item in db.ChucVu)
            {
                if (item.MaCV != 1 && item.MaCV != 2 && item.MaCV != 3)
                {
                    selectList.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList;
            try
            {
                if (ModelState.IsValid)
                {
                    db.NV.Add(nV);
                    db.SaveChanges();
                    return RedirectToAction("ThêmNhânViênTC", new { id = Encryption.encrypt(nV.MaNV.ToString()) });
                }
            }
            catch
            {
                return View("LỗiTạoNhânViên");
            }
            return View(nV);
        }

        // GET: NVs/Edit/5
        [MyAuthorize(Roles = "Admin,PM")]
        [EncryptedActionParameter]
        [ActionName("SửaNhânViên")]
        public ActionResult Edit(string id)
        {
            List<SelectListItem> selectList1 = new List<SelectListItem>();
            List<SelectListItem> selectList2 = new List<SelectListItem>();
            List<SelectListItem> selectList3 = new List<SelectListItem>();
            List<SelectListItem> selectList4 = new List<SelectListItem>();
            foreach (var item in db.ChucVu)
            {                
                  if(item.MaCV==1)
                  {
                    selectList1.Add(new SelectListItem
                        {
                            Text = item.TenCV,
                            Value = item.MaCV.ToString()
                        });
                  }
                    else if(item.MaCV==2 && item.MaCV!=1)
                    {
                    selectList2.Add(new SelectListItem
                        {
                            Text = item.TenCV,
                            Value = item.MaCV.ToString()
                        });

                    }
                else if (item.MaCV == 3 && item.MaCV != 1 && item.MaCV!=2)
                {
                    selectList3.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });

                }
                else if(item.MaCV!=1 || item.MaCV!=2 || item.MaCV!=3)
                {
                    selectList4.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV1 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList1;
            ViewBag.TenCV2 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList2;
            ViewBag.TenCV3 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList3;
            ViewBag.TenCV4 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList4;
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NV nV = db.NV.Find(x);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // POST: NVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SửaNhânViên")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,TenNV,MaCV,SDTNV,DCNV")] NV nV)
        {
            List<SelectListItem> selectList1 = new List<SelectListItem>();
            List<SelectListItem> selectList2 = new List<SelectListItem>();
            List<SelectListItem> selectList3 = new List<SelectListItem>();
            List<SelectListItem> selectList4 = new List<SelectListItem>();
            foreach (var item in db.ChucVu)
            {
                if (item.MaCV == 1)
                {
                    selectList1.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
                else if (item.MaCV == 2 && item.MaCV != 1)
                {
                    selectList2.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });

                }
                else if (item.MaCV == 3 && item.MaCV != 1 && item.MaCV != 2)
                {
                    selectList3.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });

                }
                else if (item.MaCV != 1 || item.MaCV != 2 || item.MaCV != 3)
                {
                    selectList4.Add(new SelectListItem
                    {
                        Text = item.TenCV,
                        Value = item.MaCV.ToString()
                    });
                }
            }
            ViewBag.TenCV1 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList1;
            ViewBag.TenCV2 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList2;
            ViewBag.TenCV3 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList3;
            ViewBag.TenCV4 = /*new SelectList(db.ChucVus, "MaCV", "TenCV")*/selectList4;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(nV).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return View("SửaNVTC");
                }
            }
            catch
            {
                return View("LỗiSửaNV");
            }
            return View(nV);
        }

        // GET: NVs/Delete/5
        [EncryptedActionParameter]
        [MyAuthorize(Roles = "Admin,PM")]
        [ActionName("XoáNhânViên")]
        public ActionResult Delete(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);

QLKS/Views/ChucVus/Details.cshtml
@model QLKS.ChucVu

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ChucVu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaCV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaCV)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TenCV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLKS/Views/ChucVus/LỗiChứcVụ.cshtml
@{
    ViewBag.Title = "LỗiChứcVụ";
}

<h2>Không thể thêm được chức vụ vì mã chức vụ trùng.</h2>


@Html.ActionLink("Trở về danh sách chức vụ", "QuảnLýChứcVụ", null, new { @class = "btn btn-primary1" })

QLKS/Views/ChucVus/LỗiXoáChứcVụ.cshtml
@{
    ViewBag.Title = "LỗiXoáChứcVụ";
}

<h2>Bạn không thể xóa chức vụ này !</h2>

@Html.ActionLink("Trở về danh sách chức vụ", "QuảnLýChứcVụ", null, new { @class = "btn btn-primary1" })

QLKS/Views/ChucVus/QuảnLýChứcVụ.cshtml
@model IEnumerable<QLKS.ChucVu>
@using QLKS.Models
@{
    ViewBag.Title = "Danh sách chức vụ";
}


<p style="margin-top:30px;">
    @Html.ActionLink("Thêm chức vụ", "ThêmChứcVụ",null,new { @class="btn btn-primary1"})
    @Html.ActionLink("Thêm nhân viên", "ThêmNhânViên","NVs", null, new { @class = "btn btn-primary1" })
</p>
<table style="border:1px solid black;margin-top:30px;" class="table">
    <tr style="border:1px solid black;">
        <th style="border:1px solid black;margin-top:30px;">
            @Html.DisplayNameFor(model => model.MaCV)
        </th>
        <th style="border:1px solid black;margin-top:30px;">
            @Html.DisplayNameFor(model => model.TenCV)
        </th>
        <th style="border:1px solid black;">
            <p style="text-align:center;">Chức năng</p>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr style="border:1px solid black;">
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.MaCV)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.TenCV)
        </td>
        <td style="border:1px solid black;">
            @Html.ActionLink("Sửa", "SửaChứcVụ", new { id = Encryption.encrypt(item.MaCV.ToString()) }, new { @class = "btn btn-primary1" })
            @Html.ActionLink("Xóa", "XoáChứcVụ", new { id = Encryption.encrypt(item.MaCV.ToString()) }, new { @class = "btn btn-primary1" })
        </td></tr>
}

</table>

QLKS/Views/ChucVus/SửaChứcVụ.cshtml
@model QLKS.ChucVu

@{
    ViewBag.Title = "Trang sửa chức vụ";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaCV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaCV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.TenCV)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary1" />
            </div>
        </div>
    </div>
}

<div>
    <p>@Html.ActionLink("Trở về danh sách chức vụ", "QuảnLýChứcVụ", null, new { @class = "btn btn-primary1" })</p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/ChucVus/SửaChứcVụThànhCông.cshtml
@{
    ViewBag.Title = "SửaChứcVụThànhCông";
}

<h2>Bạn đã cập nhật thành công 1 chức vụ !</h2>

@Html.ActionLink("Trở về danh sách chức vụ","QuảnLýChứcVụ",null,new { @class="btn btn-primary1"})

QLKS/Views/ChucVus/ThêmChứcVụ.cshtml
@model QLKS.ChucVu

@{
    ViewBag.Title = "Trang thêm chức vụ";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaCV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaCV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaCV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenCV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenCV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenCV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary1" />
            </div>
        </div>
    </div>
}

<div>
    <p>@Html.ActionLink("Trở về danh sách chức vụ", "QuảnLýChứcVụ", null, new { @class = "btn btn-primary1" })</p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/ChucVus/ThêmChứcVụThànhCông.cshtml
@{
    ViewBag.Title = "ThêmChứcVụThànhCông";
}

<h2>Bạn đã thêm chức vụ thành công ! Để tiếp tục thêm chức bấm vào <a href="@Url.Action("ThêmChứcVụ")"></a></h2>
@Html.ActionLink("Trở về danh sách chức vụ","QuảnLýChứcVụ",null,new { @class="btn btn-primary1"})

QLKS/Views/ChucVus/XoáChứcVụ.cshtml
@model QLKS.ChucVu

@{
    ViewBag.Title = "Trang xóa";
}


<h3>Bạn có muốn xóa chức vụ không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaCV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaCV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model=> model.TenCV)
        </dt>
        <dd>
            @Html.DisplayFor(model=>model.TenCV)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary1" /> |
            <p>@Html.ActionLink("Trở về danh sách chức vụ", "QuảnLýChứcVụ", null, new { @class = "btn btn-primary1" })</p>
        </div>
    }
</div>

QLKS/Views/ChucVus/XoáThànhCông.cshtml
@{
    ViewBag.Title = "XoáThànhCông";
}

<h2>Bạn đã xóa thành công chức vụ này!</h2>

@Html.ActionLink("Trở về danh sách chức vụ", "QuảnLýChứcVụ", null, new { @class = "btn btn-primary1" })