QLKS/Controllers/PhongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure;
using System.Text.RegularExpressions;
using PagedList;
using QLKS.Models;

namespace QLKS.Controllers
{
    [MyAuthorize(Roles ="Admin,TT")]
    public class PhongsController : Controller
    {
        private QLKSEntities2 db = new QLKSEntities2();
        private Phong phong = new Phong();
        // GET: Phongs
        [ActionName("TrangPhòng")]
        public ActionResult Index(string option, string searchString,int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            if (option == "MaPhong")
            {
                return View(db.Phong.Where(x => x.MaPhong.ToString().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "TenPhong")
            {
                return View(db.Phong.Where(x => x.TenPhong.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "LoaiPhong")
            {
                return View(db.Phong.Where(x => x.LoaiPhong.TenLoai.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "DonGia")
            {
                return View(db.Phong.Where(x => x.LoaiPhong.Dongia.ToString().Contains(searchString)).ToList().ToPagedList(pageNumber, pageSize));
            }
            else if (option == "TinhTrang")
            {
                return View(db.Phong.ToList().Where(x => x.ChuyenKieuTinhTrang.ToUpper().Contains(searchString.ToUpper())).ToList().ToPagedList(pageNumber, pageSize));
            }
            else
                return View(db.Phong.Include(i=>i.LoaiPhong).OrderBy(x=>x.MaPhong).ToPagedList(pageNumber, pageSize));
        }

        // GET: Phongs/Details/5
        [ActionName("TạoPhòngTC")]
        public ActionResult Details(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phong.Find(x);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // GET: Phongs/Create
        [ActionName("TạoPhòng")]
        public ActionResult Create()
        {
            List<SelectListItem> loaiPhong = new List<SelectListItem>();
            foreach (var item in db.LoaiPhong)
            {
                loaiPhong.Add(new SelectListItem
                {
                    Text = item.TenLoai,
                    Value = Convert.ToString(item.MaLoai)
                });
            }
            ViewBag.LoaiPhong = loaiPhong;
            return View();
        }

        // POST: Phongs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("TạoPhòng")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPhong,TenPhong,MaLoai,GhiChu,TinhTrang")] Phong phong)
        {
            List<SelectListItem> loaiPhong = new List<SelectListItem>();
            foreach (var item in db.LoaiPhong)
            {
                loaiPhong.Add(new SelectListItem
                {
                    Text = item.TenLoai,
                    Value = Convert.ToString(item.MaLoai)
                });
            }
            ViewBag.LoaiPhong = loaiPhong;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Phong.Add(phong);
                    db.SaveChanges();
                    return RedirectToAction("TạoPhòngTC",new { id=Encryption.encrypt(phong.MaPhong.ToString())});
                }
            }
            catch
            {
                return View("LỗiTạoPhòng");
            }
            return View(phong);
        }

        // GET: Phongs/Edit/5
        [ActionName("SửaPhòng")]
        public ActionResult Edit(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            List<SelectListItem> loaiPhong = new List<SelectListItem>();
            foreach (var item in db.LoaiPhong)
            {
                loaiPhong.Add(new SelectListItem
                {
                    Text = item.TenLoai,
                    Value = Convert.ToString(item.MaLoai)
                });
            }
            ViewBag.LoaiPhong = loaiPhong;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phong.FirstOrDefault(p => p.MaPhong == x);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // POST: Phongs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SửaPhòng")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPhong,TenPhong,MaLoai,GhiChu,TinhTrang")] Phong phong)
        {
            List<SelectListItem> loaiPhong = new List<SelectListItem>();
            foreach (var item in db.LoaiPhong)
            {
                loaiPhong.Add(new SelectListItem
                {
                    Text = item.TenLoai,
                    Value = Convert.ToString(item.MaLoai)
                });
            }
            ViewBag.LoaiPhong = loaiPhong;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(phong).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return View("SửaPhòngTC");
                }
            }
            catch
            {
                //return View("LỗiSửaPhòng");
            }
            return View(phong);
        }

        // GET: Phongs/Delete/5
         [ActionName("XoáPhòng")]
        public ActionResult Delete(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (decode == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phong.Find(x);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // POST: Phongs/Delete/5
        [HttpPost, ActionName("XoáPhòng")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            Phong phong = db.Phong.Find(x);
            try
            {
                if (phong.TinhTrang.Value == false)
                {
                    db.Phong.Remove(phong);
                    db.SaveChanges();
                    return View("XoáPhòngTC");
                }
                else
                    return View("DeleteConFirmed");
            }
            catch
            {
                return View("DeleteConFirmed");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKS/Views/ThuePhongs/ChiTiếtThuêPhòng.cshtml
@model IEnumerable<QLKS.ChiTietThuePhong>
@using QLKS.Models

<table style="border:1px solid black;margin-top:30px;" class="table">
    <tr style="border:1px solid black;">
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.SoLuongKhach)
        </th>
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.KhachHang.TenKhachHang)
        </th>
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.ThuePhong.MaThuePhong)
        </th>
        <th style="border:1px solid black;">
            Chức năng
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="border:1px solid black;">
            <td style="border:1px solid black;">
                @Html.DisplayFor(modelItem => item.SoLuongKhach)
            </td>
            <td style="border:1px solid black;">
                @Html.DisplayFor(modelItem => item.KhachHang.TenKhachHang)
            </td>
            <td style="border:1px solid black;">
                @Html.DisplayFor(modelItem => item.ThuePhong.MaThuePhong)
            </td>
            <td style="border:1px solid black;">
                @Html.ActionLink("Sửa", "SửaChiTiếtThuêPhòng", new { id = Encryption.encrypt(item.MaThuePhong.ToString()), khachhang = Encryption.encrypt(item.MaKhachHang.ToString()) }, new { @class = "btn btn-primary1" })
                @Html.ActionLink("Xóa", "XoáChiTiếtThuêPhòng", new { id = Encryption.encrypt(item.MaThuePhong.ToString()), khachhang = Encryption.encrypt(item.MaKhachHang.ToString()) }, new { @class = "btn btn-primary1" })
            </td>
        </tr>
    }

</table>

QLKS/Views/ThuePhongs/Details.cshtml
@model QLKS.ThuePhong

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ThuePhong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgayBatDauThue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayBatDauThue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiKhach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiKhach)
        </dd>

      

        <dt>
            @Html.DisplayNameFor(model => model.Phong.TenPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phong.TenPhong)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaThuePhong }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLKS/Views/ThuePhongs/LỗiSửaTP.cshtml
@{
    ViewBag.Title = "LỗiSửaTP";
}

<h2>Không thể sửa thuê phòng!</h2>

@Html.ActionLink("Trở về danh sách thuê phòng","TrangThuêPhòng",null,new { @class="btn btn-primary1"})

QLKS/Views/ThuePhongs/LỗiXoáThuêPhòng.cshtml
@{
    ViewBag.Title = "LỗiXoáThuêPhòng";
}

<h2>Không thể xóa thuê phòng!</h2>

@Html.ActionLink("Trở về danh sách thuê phòng", "TrangThuêPhòng", null, new { @class = "btn btn-primary1" })

QLKS/Views/ThuePhongs/SửaChiTiếtThuêPhòng.cshtml
@model QLKS.ChiTietThuePhong

@{
    ViewBag.Title = "SửaChiTiếtThuêPhòng";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaThuePhong)

        @Html.HiddenFor(model => model.MaKhachHang)
        <div class="form-group">
            @Html.LabelFor(model => model.MaThuePhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MaThuePhong, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MaThuePhong, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.KhachHang.TenKhachHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaKhachHang,(IEnumerable<SelectListItem>)ViewBag.MaKhachHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongKhach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> soLuong = new List<SelectListItem>();
                    soLuong.Add(new SelectListItem
                    {
                        Text = "1",
                        Value = (1).ToString()

                    });
                    soLuong.Add(new SelectListItem
                    {
                        Text = "2",
                        Value = (2).ToString(),
                    });
                    soLuong.Add(new SelectListItem
                    {
                        Text = "3",
                        Value = (3).ToString(),
                    });
                }
                @Html.DropDownListFor(model => model.SoLuongKhach, soLuong, "--Select status--")
                @Html.ValidationMessageFor(model => model.SoLuongKhach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary1" />
            </div>
        </div>
    </div>
                    }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/ThuePhongs/SửaThuêPhòng.cshtml
@model QLKS.ThuePhong

@{
    ViewBag.Title = "Sửa thuê phòng";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaThuePhong)

        <div class="form-group">
            @Html.LabelFor(model => model.MaThuePhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MaThuePhong, new { htmlAttributes = new { @class = "form-control",@readonly="readonly" } })
                @Html.ValidationMessageFor(model => model.MaThuePhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phong.TenPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaPhong, (IEnumerable<SelectListItem>)ViewBag.MaPhong, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayBatDauThue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayBatDauThue,"{0:dd/MM/yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayBatDauThue, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary1" />
            </div>
        </div>
    </div>
                    }

<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/ThuePhongs/SửaThànhCông.cshtml
@{
    ViewBag.Title = "SửaThànhCông";
}

<h2>Sửa thành công chi tiết thuê phòng!</h2>

@Html.ActionLink("Trở về danh sách thuê phòng", "TrangThuêPhòng", null, new { @class = "btn btn-primary1" })

QLKS/Views/ThuePhongs/ThuêPhòng.cshtml
@model QLKS.ThuePhong

@{
    ViewBag.Title = "Thuê phòng";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Phiếu thuê phòng</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.MaPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaPhong, (IEnumerable<SelectListItem>)ViewBag.MaPhong, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPhong, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NgayBatDauThue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayBatDauThue,"{0:dd/MM/yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayBatDauThue, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thuê" class="btn btn-primary1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về danh sách thuê phòng", "TrangThuêPhòng", null, new { @class = "btn btn-primary1" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/ThuePhongs/ThànhCông.cshtml
@model QLKS.ThuePhong
@{
    ViewBag.Title = "ThànhCông";
}

<h2>Bạn đã thuê phòng thành công! Để thuê phòng tiếp bấm vào <a href="@Url.Action("ThuêPhòng")">đây</a> </h2>
@Html.ActionLink("Tạo chi tiết thuê phòng","TạoChiTiếtThuêPhòng","ChiTietThuePhongs",null,new { @class="btn btn-primary1"})
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaPhong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NgayBatDauThue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayBatDauThue)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phong.TenPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phong.TenPhong)
        </dd>

    </dl>
</div>
@Html.ActionLink("Về danh sách thuê phòng","TrangThuêPhòng",null,new { @class="btn btn-primary1",style="margin-left: 20px;"})

QLKS/Views/ThuePhongs/TrangThuêPhòng.cshtml
@model IEnumerable<QLKS.ThuePhong>
@using QLKS.Models
@{
    ViewBag.Title = "Danh sách thuê phòng";
}


<p style="margin-top:20px;margin-bottom:20px;">
    @Html.ActionLink("Thuê phòng", "ThuêPhòng", null,new { @class="btn btn-primary1"})
    @Html.ActionLink("Thông tin phòng", "TrangPhòng","Phongs", null, new { @class = "btn btn-primary1" })
    @Html.ActionLink("Thêm khách hàng", "ThêmKháchHàng", "KhachHangs", null, new { @class = "btn btn-primary1" })
</p>
<table style="border:1px solid black;margin-bottom:20px;" class="table">
    <tr style="border:1px solid black;">
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.MaThuePhong)
        </th>
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.MaPhong)
        </th>
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.Phong.TenPhong)
        </th>
        <th style="border:1px solid black;">
            @Html.DisplayNameFor(model => model.NgayBatDauThue)
        </th>
        <th style="border:1px solid black;">
            <p style="text-align:center;">Chức năng</p>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr style="border:1px solid black;">
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.MaThuePhong)
        </td>
        <td style="border:1px solid black;">
          
            @Html.DisplayFor(modelItem => item.MaPhong)
        </td>
        <td style="border:1px solid black;">
         
            @Html.DisplayFor(modelItem => item.Phong.TenPhong)
        </td>
        <td style="border:1px solid black;">
            @Html.DisplayFor(modelItem => item.NgayBatDauThue)
        </td>
        <td style="border:1px solid black;">
            @Html.ActionLink("Sửa", "SửaThuêPhòng", new { id=Encryption.encrypt(item.MaThuePhong.ToString()) },new { @class="btn btn-primary1"})
            @Html.ActionLink("Xóa", "XoáThuêPhòng", new { id=Encryption.encrypt(item.MaThuePhong.ToString()) },new { @class = "btn btn-primary1" })
        </td>
    </tr>
}

</table>
<hr />
<div>
    <h2>Chi tiết thuê phòng</h2>
    <input class="btn btn-primary1" type="button" name="submit" value="Thêm chi tiết" id="btnShow" />
    <div id="dvShow"></div>
    @Html.Action("ChiTiếtThuêPhòng")
</div>
<script>
                            $(document).ready(function () {
                                $("#btnShow").click(function () {
                                    $.ajax({
                                        url: '@Url.Action("TạoChiTiếtThuêPhòng")',
                                        type: 'get',
                                        success: function (vHtml) {
                                            $("#dvShow").html("");
                                            $("#dvShow").html(vHtml);
                                        }
                                    })
                                })
                            })

</script>

QLKS/Views/ThuePhongs/TạoChiTiếtThuêPhòng.cshtml
@model QLKS.ChiTietThuePhong

@{
    ViewBag.Title = "TạoChiTiếtThuêPhòng";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ThuePhong.MaThuePhong,"Mã Thuê Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model=>model.MaThuePhong, (IEnumerable<SelectListItem>)ViewBag.MaThuePhong, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaThuePhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KhachHang.TenKhachHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaKhachHang, (IEnumerable<SelectListItem>)ViewBag.MaKhachHang, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongKhach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> soLuong = new List<SelectListItem>();
                    soLuong.Add(new SelectListItem
                    {
                        Text = "1",
                        Value = (1).ToString()

                    });
                    soLuong.Add(new SelectListItem
                    {
                        Text = "2",
                        Value = (2).ToString(),
                    });
                    soLuong.Add(new SelectListItem
                    {
                        Text = "3",
                        Value = (3).ToString(),
                    });
                }
                @Html.DropDownListFor(model => model.SoLuongKhach, soLuong, "--Select status--")
                @Html.ValidationMessageFor(model => model.SoLuongKhach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary1" />
            </div>
        </div>
    </div>
                    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLKS/Views/ThuePhongs/XoáChiTiếtThuêPhòng.cshtml
@model QLKS.ChiTietThuePhong

@{
    ViewBag.Title = "XoáChiTiếtThuêPhòng";
}


<h3>Bạn mún xóa chi tiết thuê phòng không?</h3>
<h2 style="color:red">Chú ý: nếu xóa chi tiết thuê phòng sẽ xóa lun thuê phòng và ở trang chi tiết hóa đơn mã thuê phòng sẽ thống.</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoLuongKhach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongKhach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKhachHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKhachHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThuePhong.MaThuePhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThuePhong.MaThuePhong)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div style="margin-left:50px;" class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary1" /> 
        </div>
    }
</div>

QLKS/Views/ThuePhongs/XoáThuêPhòng.cshtml
@model QLKS.ThuePhong

@{
    ViewBag.Title = "Xóa thuê phòng";
}


<h3 style="color:red">Bạn muốn xóa thuê phòng không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaThuePhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaThuePhong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaPhong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phong.TenPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phong.TenPhong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NgayBatDauThue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayBatDauThue)
        </dd>
        </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary1" />
        </div>
    }
</div>

QLKS/Views/ThuePhongs/XoáThànhCôngTP.cshtml
@{
    ViewBag.Title = "XoáThànhCôngTP";
}

<h2>Xoá Thành Công thành công</h2>

@Html.ActionLink("Trở về danh sách thuê phòng", "TrangThuêPhòng", null, new { @class = "btn btn-primary1" })