QLKS/Controllers/HDsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS;
using QLKS.Models;

namespace QLKS.Controllers
{
    [MyAuthorize(Roles = "AM,Admin")]
    public class HDsController : Controller
    {
        private QLKSEntities2 db = new QLKSEntities2();
        private ThuePhong thuePhong = new ThuePhong();
        NV nV = new NV();
        // GET: HDs
        [MyAuthorize(Roles = "KT")]
        [ActionName("QuảnLýHóaĐơn")]
        public ActionResult Index()
        {
            var hDs = db.HD.Include(X=>X.NV).Include(x=>x.KhachHang).ToList();
            return View(hDs);
        }

        // GET: HDs/Details/5
        public ActionResult Details(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HD hD = db.HD.Find(x);
            if (hD == null)
            {
                return HttpNotFound();
            }
            return View(hD);
        }

        // GET: HDs/Create
        [ActionName("ThanhToánHóaĐơn")]
        public ActionResult Create()
        {
            List<SelectListItem> tenNV = new List<SelectListItem>();
            List<SelectListItem> tenKH = new List<SelectListItem>();
            foreach (var item in db.NV)
            {
                if (item.ChucVu.TenCV == "Ke Toan" || item.ChucVu.TenCV == "Ke Toan Truong")
                {

                    tenNV.Add(new SelectListItem
                    {
                        Text = item.TenNV,
                        Value = item.MaNV.ToString()
                    });
                }
            }
            ViewBag.MaNV = tenNV;
            foreach(var item in db.KhachHang)
            {
                tenKH.Add(new SelectListItem
                {
                    Text = item.TenKhachHang,
                    Value = item.MaKhachHang.ToString()
                });
            }
            ViewBag.MaKH = /*new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang")*/tenKH;
            return View();
        }

        // POST: HDs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("ThanhToánHóaĐơn")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKhachHang,MaNV,TongTien")] HD hD)
        {
            List<SelectListItem> tenKH = new List<SelectListItem>();
            foreach (var item in db.KhachHang)
            {
                tenKH.Add(new SelectListItem
                {
                    Text = item.TenKhachHang,
                    Value = Convert.ToString(item.MaKhachHang)
                });
            }
            ViewBag.MaKH = /*new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang")*/tenKH;
            List<SelectListItem> tenNV = new List<SelectListItem>();
            foreach (var item in db.NV)
            {
                if (item.ChucVu.TenCV == "Ke Toan" || item.ChucVu.TenCV == "Ke Toan Truong")
                {

                    tenNV.Add(new SelectListItem
                    {
                        Text = item.TenNV,
                        Value = Convert.ToString(item.MaNV)
                    });
                }
            }
            ViewBag.MaNV = tenNV;
            if (ModelState.IsValid)
            {
                db.HD.Add(hD);
                db.SaveChanges();
                return View("ThanhToánHoáTC");
            }

            return View(hD);
        }

        // GET: HDs/Edit/5
        [ActionName("SửaHóaĐơn")]
        public ActionResult Edit(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            List<SelectListItem> tenKH = new List<SelectListItem>();
            foreach (var item in db.KhachHang)
            {
                tenKH.Add(new SelectListItem
                {
                    Text = item.TenKhachHang,
                    Value = Convert.ToString(item.MaKhachHang)
                });
            }
            ViewBag.MaKH = /*new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang")*/tenKH;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HD hD = db.HD.Find(x);
            if (hD == null)
            {
                return HttpNotFound();
            }
            List<SelectListItem> tenNV = new List<SelectListItem>();
            foreach (var item in db.NV)
            {
                if (item.ChucVu.TenCV == "Ke Toan" || item.ChucVu.TenCV == "Ke Toan Truong")
                {

                    tenNV.Add(new SelectListItem
                    {
                        Text = item.TenNV,
                        Value = Convert.ToString(item.MaNV)
                    });
                }
            }
            ViewBag.MaNV = tenNV;
            return View(hD);
        }

        // POST: HDs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SửaHóaĐơn")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHD,MaKhachHang,MaNV,TongTien")] HD hD)
        {
            List<SelectListItem> tenKH = new List<SelectListItem>();
            foreach (var item in db.KhachHang)
            {
                tenKH.Add(new SelectListItem
                {
                    Text = item.TenKhachHang,
                    Value = Convert.ToString(item.MaKhachHang)
                });
            }
            ViewBag.MaKH = /*new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang")*/tenKH;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(hD).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return View("SửaThànhCôngHóaĐơn");
                }
            }
            catch
            {
                return View("LỗiKhiSửaHĐ");
            }
            ViewBag.MaTP = new SelectList(db.ThuePhong, "MaThuePhong", "MaThuePhong", thuePhong.MaThuePhong);
            List<SelectListItem> tenNV = new List<SelectListItem>();
            foreach (var item in db.NV)
            {
                if (item.ChucVu.TenCV == "Ke Toan" || item.ChucVu.TenCV == "Ke Toan Truong")
                {

                    tenNV.Add(new SelectListItem
                    {
                        Text = item.TenNV,
                        Value = Convert.ToString(item.MaNV)
                    });
                }
            }
            ViewBag.MaNV = tenNV;
            return View(hD);
        }

        // GET: HDs/Delete/5
        [ActionName("XóaHóaĐơn")]
        public ActionResult Delete(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HD hD = db.HD.Find(x);
            if (hD == null)
            {
                return HttpNotFound();
            }
            return View(hD);
        }

        // POST: HDs/Delete/5
        [HttpPost, ActionName("XóaHóaĐơn")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var decode = Encryption.decrypt(id);
            int x = int.Parse(decode);
            HD hD = db.HD.Find(x);
            try {
                db.HD.Remove(hD);
                db.SaveChanges();
                return View("XoáTCHD");
            }
            catch
            {
                return View("LỗiKhiXóaHD");
            }
            
        }
        //Chi Tiết Hóa Đơn

        [ActionName("ChiTiếtHóaĐơn")]
        public ActionResult ChiTietHoaDon()
        {
            var chiTietHoaDons = db.ChiTietHoaDon.Include(c => c.HD).Include(c => c.ThuePhong);
            return PartialView(chiTietHoaDons.ToList());
        }

        // GET: ChiTietHoaDons/Create
        [ActionName("TạoChiTiếtHóaĐơn")]
        public ActionResult TaoChiTietHoaDon()
        {
            ViewBag.MaHD = new SelectList(db.HD, "MaHD", "MaHD");
            ViewBag.MaThuePhong = new SelectList(db.ThuePhong, "MaThuePhong", "MaThuePhong");
            return PartialView();
        }

        // POST: ChiTietHoaDons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("TạoChiTiếtHóaĐơn")]
        public ActionResult TaoChiTietHoaDon([Bind(Include = "MaHD,MaThuePhong,SoNgayThue")] ChiTietHoaDon chiTietHoaDon)
        {
            if (ModelState.IsValid)
            {
                db.ChiTietHoaDon.Add(chiTietHoaDon);
                db.SaveChanges();
                return RedirectToAction("QuảnLýHóaĐơn");
            }

            ViewBag.MaHD = new SelectList(db.HD, "MaHD", "MaHD", chiTietHoaDon.MaHD);
            ViewBag.MaThuePhong = new SelectList(db.ThuePhong, "MaThuePhong", "MaThuePhong", chiTietHoaDon.MaThuePhong);
            return PartialView(chiTietHoaDon);
        }


        // GET: ChiTietHoaDons/Edit/5
        [ActionName("SửaChiTiếtHóaĐơn")]
        public ActionResult SuaChiTietHoaDon(string id, string maThuePhong)
        {
            var decode = Encryption.decrypt(id);

QLKS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" type="image/ico" href="~/Content/Icons8-Windows-8-City-Hotel.ico">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Welcome to Luxury Hotel!</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="description" content="The description of my page" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>

<body style="margin:0">

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/Homeiocn.png" />
                @Html.ActionLink("LUXURY HOTEL", "TrangChủ", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important;font-family:'Lucida Handwriting'" })

            </div>
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-collapse collapse navbar-right" style="color:white">
                    @if (Request.IsAuthenticated)
                    {
                        TaiKhoan user = new TaiKhoan();
                        user = Session["User"] as TaiKhoan;
                        if (user != null)
                        {
                            if (user.Roles == "Admin")
                            {
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/personnelicon.png" />
                                @Html.ActionLink("Nhân Viên", "TrangNhânViên", "NVs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/roomicon.png" />
                                @Html.ActionLink("Phòng", "TrangPhòng", "Phongs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/customericon.png" />
                                @Html.ActionLink("Khách Hàng", "QuảnLýKháchHàng", "KhachHangs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                                <img style="float:left;width:30px;margin-right:10px;height:35px;margin-top:10px;" src="~/Content/billicon.png" />
                                @Html.ActionLink("Hóa Đơn", "QuảnLýHóaĐơn", "HDs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/moneyicon.png" />
                                @Html.ActionLink("Doanh Thu", "QuảnLýDoanhThu", "DoanhThus", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                            }
                            else if (user.Roles == "KT" || user.Roles == "AM")
                            {
                                <img style="float:left;width:30px;margin-right:10px;height:35px;margin-top:10px;" src="~/Content/billicon.png" />
                                @Html.ActionLink("Hóa Đơn", "QuảnLýHóaĐơn", "HDs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/moneyicon.png" />
                                @Html.ActionLink("Doanh Thu", "QuảnLýDoanhThu", "DoanhThus", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                            }
                            else if (user.Roles == "TT")
                            {
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/roomicon.png" />
                                @Html.ActionLink("Phòng", "TrangPhòng", "Phongs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/customericon.png" />
                                @Html.ActionLink("Khách Hàng", "QuảnLýKháchHàng", "KhachHangs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                            }
                            else if (user.Roles == "PM")
                            {
                                <img style="float:left;width:30px;margin-right:10px;margin-top:10px;" src="~/Content/personnelicon.png" />
                                @Html.ActionLink("Nhân Viên", "TrangNhânViên", "NVs", new { area = "" }, new { @class = "navbar-brand", @style = "color:white !important" })
                            }
                        }

                    }

                </div>

            </div>
            <ul class="nav navbar-collapse collapse navbar-right">
                <li>@Html.Action("TruyenDuLieu", "Home")</li>
            </ul>
        </div>
    </div>
   

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer id="footer">
            <div class="fpart-first">
                <div style="width:100%;" class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <h5>Về chúng tôi</h5>
                            <ul>
                                <li>@Html.ActionLink("Về Luxury Hotel", "About", "Home", null, new { @class = "about1" })</li>
                            </ul>
                        </div>
                        <div class="col-md-4 contact">
                            <h5>Liên Hệ</h5>
                            <ul>
                                <li>@Html.ActionLink("Liên hệ chúng tôi", "Contact", "Home", null, new { @class = "about1" })</li>
                            </ul>
                        </div>
                        <div class="col-md-5 contact">
                            <h5>Địa chỉ</h5>
                            <ul>
                                <li><span>Sư Vạn Hạnh Phường 13 Quận 10</span></li>
                                <li><span>Ngày thành lập: 7/4/2016</span></li>
                                <li><span>Sđt: +08 38629233</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <h4 class="copy">&copy; @DateTime.Now.Year - Copyright Luxury Hotel</h4>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>